"""Agregar campo observaciones a Pet

Revision ID: da33d25ac101
Revises: 48aadc573348
Create Date: 2025-02-25 08:47:42.713320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da33d25ac101'
down_revision = '48aadc573348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observations', sa.Text(), nullable=True))

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_species_name'), ['name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_species_name'), type_='unique')

    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('observations')

    # ### end Alembic commands ###
